name: calcule_imc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Used to compare objects
  equatable: ^2.0.5
  # Used as state manager 
  flutter_bloc: ^8.1.2
  # Used to implement tests for bloc
  bloc_test: ^9.1.1
  # Used to import curpetino icons
  cupertino_icons: ^1.0.2
  # Used to enhance project functionality
  dartz: ^0.10.1
  # Used to inject dependencies
  injectable: ^2.1.0
  # Used to provide injection dependencies
  get_it: ^7.2.0
  # Used to navigate in app
  go_router: ^6.0.6
  # Used to import google fonts to project
  google_fonts: ^4.0.3
  #
  intl: ^0.18.0
  #
  flutter_svg: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Used to generate instances to injection dependencies
  injectable_generator: ^2.1.3
  # Used to generate code
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
